# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:


    providers:
        hero_provider:
          id: "rpg.security.hero.user.provider"

    firewalls:
        hero_register:
            pattern:   ^/char/characters/
            methods: [POST]
            anonymous: ~

        hero_secured:
            pattern: ^/char/
            stateless: true
            provider: hero_provider
            guard:
                authenticators:
                    - "rpg.security.hero.authenticator"

        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
